### ISSUE TITLE
Error in `/usr/local/bin/python3

### ISSUE THREAD

**Issue by devil67** [D4Vinci/PasteJacker#1]
Hi,when i press number 1 for windows i got this one

`[1] Windows
  [2] Linux
  [3] Exit
   │
   └──[PasteJacker]──[~]─[menu]: 1
*** Error in `/usr/local/bin/python3': free(): invalid pointer: 0x00007f9848584b18 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f98477697e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f984777237a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f984777653c]
/usr/local/bin/python3(PyOS_Readline+0x12d)[0x49eac7]
/usr/local/bin/python3[0x456787]
/usr/local/bin/python3(_PyMethodDef_RawFastCallKeywords+0xf9)[0x4bfd09]
/usr/local/bin/python3(_PyCFunction_FastCallKeywords+0x20)[0x4bfbf0]
/usr/local/bin/python3(_PyEval_EvalFrameDefault+0x45fa)[0x536dba]
/usr/local/bin/python3[0x4c1748]
/usr/local/bin/python3(_PyEval_EvalFrameDefault+0x695)[0x532e55]
/usr/local/bin/python3(_PyFunction_FastCallKeywords+0x102)[0x4c1512]
/usr/local/bin/python3(_PyEval_EvalFrameDefault+0x695)[0x532e55]
/usr/local/bin/python3(_PyEval_EvalCodeWithName+0x144)[0x531cb4]
/usr/local/bin/python3(PyEval_EvalCode+0x23)[0x531b63]
/usr/local/bin/python3[0x5dd4e2]
/usr/local/bin/python3(PyRun_FileExFlags+0x9a)[0x5dd91a]
/usr/local/bin/python3(PyRun_SimpleFileExFlags+0x1a7)[0x5dd707]
/usr/local/bin/python3[0x5b6731]
/usr/local/bin/python3(_Py_UnixMain+0x3a)[0x5b63fa]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f9847712830]
/usr/local/bin/python3(_start+0x29)[0x5b62e9]
======= Memory map: ========
00400000-006c2000 r-xp 00000000 08:01 21500541                           /usr/local/bin/python3.7
008c1000-008c2000 r--p 002c1000 08:01 21500541                           /usr/local/bin/python3.7
008c2000-0092b000 rw-p 002c2000 08:01 21500541                           /usr/local/bin/python3.7
0092b000-0094c000 rw-p 00000000 00:00 0 
01a39000-01e63000 rw-p 00000000 00:00 0                                  [heap]
7f983c000000-7f983c021000 rw-p 00000000 00:00 0 
7f983c021000-7f9840000000 ---p 00000000 00:00 0 
7f9841725000-7f984173b000 r-xp 00000000 08:01 18092642                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f984173b000-7f984193a000 ---p 00016000 08:01 18092642                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f984193a000-7f984193b000 rw-p 00015000 08:01 18092642                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f984193b000-7f9841952000 r-xp 00000000 08:01 18092758                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f9841952000-7f9841b52000 ---p 00017000 08:01 18092758                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f9841b52000-7f9841b53000 r--p 00017000 08:01 18092758                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f9841b53000-7f9841b54000 rw-p 00018000 08:01 18092758                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f9841b54000-7f9841b56000 rw-p 00000000 00:00 0 
7f9841b56000-7f9841b5b000 r-xp 00000000 08:01 18092703                   /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f9841b5b000-7f9841d5b000 ---p 00005000 08:01 18092703                   /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f9841d5b000-7f9841d5c000 r--p 00005000 08:01 18092703                   /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f9841d5c000-7f9841d5d000 rw-p 00006000 08:01 18092703                   /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f9841d5d000-7f9841d5f000 r-xp 00000000 08:01 18092711                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f9841d5f000-7f9841f5e000 ---p 00002000 08:01 18092711                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f9841f5e000-7f9841f5f000 r--p 00001000 08:01 18092711                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f9841f5f000-7f9841f60000 rw-p 00002000 08:01 18092711                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f9841f60000-7f9841f6b000 r-xp 00000000 08:01 18092705                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f9841f6b000-7f984216a000 ---p 0000b000 08:01 18092705                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f984216a000-7f984216b000 r--p 0000a000 08:01 18092705                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f984216b000-7f984216c000 rw-p 0000b000 08:01 18092705                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f984216c000-7f9842232000 rw-p 00000000 00:00 0 
7f9842232000-7f9842242000 r-xp 00000000 08:01 23337899                   /usr/local/lib/python3.7/lib-dynload/_asyncio.cpython-37m-x86_64-linux-gnu.so
7f9842242000-7f9842441000 ---p 00010000 08:01 23337899                   /usr/local/lib/python3.7/lib-dynload/_asyncio.cpython-37m-x86_64-linux-gnu.so
7f9842441000-7f9842442000 r--p 0000f000 08:01 23337899                   /usr/local/lib/python3.7/lib-dynload/_asyncio.cpython-37m-x86_64-linux-gnu.so
7f9842442000-7f9842446000 rw-p 00010000 08:01 23337899                   /usr/local/lib/python3.7/lib-dynload/_asyncio.cpython-37m-x86_64-linux-gnu.so
7f9842446000-7f9842447000 r-xp 00000000 08:01 23337891                   /usr/local/lib/python3.7/lib-dynload/_contextvars.cpython-37m-x86_64-linux-gnu.so
7f9842447000-7f9842646000 ---p 00001000 08:01 23337891                   /usr/local/lib/python3.7/lib-dynload/_contextvars.cpython-37m-x86_64-linux-gnu.so
7f9842646000-7f9842647000 r--p 00000000 08:01 23337891                   /usr/local/lib/python3.7/lib-dynload/_contextvars.cpython-37m-x86_64-linux-gnu.so
7f9842647000-7f9842648000 rw-p 00001000 08:01 23337891                   /usr/local/lib/python3.7/lib-dynload/_contextvars.cpython-37m-x86_64-linux-gnu.so
7f9842648000-7f9842708000 rw-p 00000000 00:00 0 
7f9842708000-7f98427f0000 r-xp 00000000 08:01 23337907                   /usr/local/lib/python3.7/lib-dynload/unicodedata.cpython-37m-x86_64-linux-gnu.so
7f98427f0000-7f98429f0000 ---p 000e8000 08:01 23337907                   /usr/local/lib/python3.7/lib-dynload/unicodedata.cpython-37m-x86_64-linux-gnu.so
7f98429f0000-7f98429f1000 r--p 000e8000 08:01 23337907                   /usr/local/lib/python3.7/lib-dynload/unicodedata.cpython-37m-x86_64-linux-gnu.so
7f98429f1000-7f9842a0e000 rw-p 000e9000 08:01 23337907                   /usr/local/lib/python3.7/lib-dynload/unicodedata.cpython-37m-x86_64-linux-gnu.so
7f9842a0e000-7f9842a4e000 rw-p 00000000 00:00 0 
7f9842a4e000-7f9842aa8000 r-xp 00000000 08:01 23337894                   /usr/local/lib/python3.7/lib-dynload/_decimal.cpython-37m-x86_64-linux-gnu.so
7f9842aa8000-7f9842ca7000 ---p 0005a000 08:01 23337894                   /usr/local/lib/python3.7/lib-dynload/_decimal.cpython-37m-x86_64-linux-gnu.so
7f9842ca7000-7f9842ca8000 r--p 00059000 08:01 23337894                   /usr/local/lib/python3.7/lib-dynload/_decimal.cpython-37m-x86_64-linux-gnu.so
7f9842ca8000-7f9842cb1000 rw-p 0005a000 08:01 23337894                   /usr/local/lib/python3.7/lib-dynload/_decimal.cpython-37m-x86_64-linux-gnu.so
7f9842cb1000-7f9842cf1000 rw-p 00000000 00:00 0 
7f9842cf1000-7f9842cf3000 r-xp 00000000 08:01 24647847                   /usr/local/lib/python3.7/site-packages/MarkupSafe-1.0-py3.7-linux-x86_64.egg/markupsafe/_speedups.cpython-37m-x86_64-linux-gnu.so
7f9842cf3000-7f9842ef2000 ---p 00002000 08:01 24647847                   /usr/local/lib/python3.7/site-packages/MarkupSafe-1.0-py3.7-linux-x86_64.egg/markupsafe/_speedups.cpython-37m-x86_64-linux-gnu.so
7f9842ef2000-7f9842ef3000 r--p 00001000 08:01 24647847                   /usr/local/lib/python3.7/site-packages/MarkupSafe-1.0-py3.7-linux-x86_64.egg/markupsafe/_speedups.cpython-37m-x86_64-linux-gnu.so
7f9842ef3000-7f9842ef4000 rw-p 00002000 08:01 24647847                   /usr/local/lib/python3.7/site-packages/MarkupSafe-1.0-py3.7-linux-x86_64.egg/markupsafe/_speedups.cpython-37m-x86_64-linux-gnu.so
7f9842ef4000-7f9842f10000 r-xp 00000000 08:01 23337904                   /usr/local/lib/python3.7/lib-dynload/_pickle.cpython-37m-x86_64-linux-gnu.so
7f9842f10000-7f984310f000 ---p 0001c000 08:01 23337904                   /usr/local/lib/python3.7/lib-dynload/_pickle.cpython-37m-x86_64-linux-gnu.so
7f984310f000-7f9843110000 r--p 0001b000 08:01 23337904                   /usr/local/lib/python3.7/lib-dynload/_pickle.cpython-37m-x86_64-linux-gnu.so
7f9843110000-7f9843114000 rw-p 0001c000 08:01 23337904                   /usr/local/lib/python3.7/lib-dynload/_pickle.cpython-37m-x86_64-linux-gnu.so
7f9843114000-7f9843154000 rw-p 00000000 00:00 0 
7f9843154000-7f9843165000 r-xp 00000000 08:01 23337888                   /usr/local/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so
7f9843165000-7f9843364000 ---p 00011000 08:01 23337888                   /usr/local/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so
7f9843364000-7f9843365000 r--p 00010000 08:01 23337888                   /usr/local/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so
7f9843365000-7f9843366000 rw-p 00011000 08:01 23337888                   /usr/local/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so
7f9843366000-7f9843466000 rw-p 00000000 00:00 0 
7f9843466000-7f98434c4000 r-xp 00000000 08:01 18092772                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f98434c4000-7f98436c4000 ---p 0005e000 08:01 18092772                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f98436c4000-7f98436c8000 r--p 0005e000 08:01 18092772                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f98436c8000-7f98436cf000 rw-p 00062000 08:01 18092772                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f98436cf000-7f98436e9000 r-xp 00000000 08:01 23337916                   /usr/local/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
7f98436e9000-7f98438e8000 ---p 0001a000 08:01 23337916                   /usr/local/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
7f98438e8000-7f98438e9000 r--p 00019000 08:01 23337916                   /usr/local/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
7f98438e9000-7f98438ef000 rw-p 0001a000 08:01 23337916                   /usr/local/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
7f98438ef000-7f9843980000 rw-p 00000000 00:00 0 
7f9843980000-7f98439a5000 r-xp 00000000 08:01 18092778                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f98439a5000-7f9843ba4000 ---p 00025000 08:01 18092778                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f9843ba4000-7f9843ba8000 r--p 00024000 08:01 18092778                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f9843ba8000-7f9843ba9000 rw-p 00028000 08:01 18092778                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f9843ba9000-7f9843be6000 r-xp 00000000 08:01 24647783                   /usr/local/lib/python3.7/site-packages/readline-6.2.4.1-py3.7-linux-x86_64.egg/readline.cpython-37m-x86_64-linux-gnu.so
7f9843be6000-7f9843de5000 ---p 0003d000 08:01 24647783                   /usr/local/lib/python3.7/site-packages/readline-6.2.4.1-py3.7-linux-x86_64.egg/readline.cpython-37m-x86_64-linux-gnu.so
7f9843de5000-7f9843de7000 r--p 0003c000 08:01 24647783                   /usr/local/lib/python3.7/site-packages/readline-6.2.4.1-py3.7-linux-x86_64.egg/readline.cpython-37m-x86_64-linux-gnu.so
7f9843de7000-7f9843dee000 rw-p 0003e000 08:01 24647783                   /usr/local/lib/python3.7/site-packages/readline-6.2.4.1-py3.7-linux-x86_64.egg/readline.cpython-37m-x86_64-linux-gnu.so
7f9843dee000-7f9843ff0000 rw-p 00000000 00:00 0 
7f9843ff0000-7f9843ff1000 r-xp 00000000 08:01 23337915                   /usr/local/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so
7f9843ff1000-7f98441f0000 ---p 00001000 08:01 23337915                   /usr/local/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so
7f98441f0000-7f98441f1000 r--p 00000000 08:01 23337915                   /usr/local/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so
7f98441f1000-7f98441f2000 rw-p 00001000 08:01 23337915                   /usr/local/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so
7f98441f2000-7f98442b2000 rw-p 00000000 00:00 0 
7f98442b2000-7f98442cb000 r-xp 00000000 08:01 23337901                   /usr/local/lib/python3.7/lib-dynload/_socket.cpython-37m-x86_64-linux-gnu.so
7f98442cb000-7f98444ca000 ---p 00019000 08:01 23337901                   /usr/local/lib/python3.7/lib-dynload/_socket.cpython-37m-x86_64-linux-gnu.so
7f98444ca000-7f98444cb000 r--p 00018000 08:01 23337901                   /usr/local/lib/python3.7/lib-dynload/_socket.cpython-37m-x86_64-linux-gnu.so
7f98444cb000-7f98444d1000 rw-p 00019000 08:01 23337901                   /usr/local/lib/python3.7/lib-dynload/_socket.cpython-37m-x86_64-linux-gnu.so
7f98444d1000-7f98444d5000 r-xp 00000000 08:01 23337880                   /usr/local/lib/python3.7/lib-dynload/_random.cpython-37m-x86_64-linux-gnu.so
7f98444d5000-7f98446d4000 ---p 00004000 08:01 23337880                   /usr/local/lib/python3.7/lib-dynload/_random.cpython-37m-x86_64-linux-gnu.so
7f98446d4000-7f98446d5000 r--p 00003000 08:01 23337880                   /usr/local/lib/python3.7/lib-dynload/_random.cpython-37m-x86_64-linux-gnu.so
7f98446d5000-7f98446d6000 rw-p 00004000 08:01 23337880                   /usr/local/lib/python3.7/lib-dynload/_random.cpython-37m-x86_64-linux-gnu.so
7f98446d6000-7f98446d8000 r-xp 00000000 08:01 23337879                   /usr/local/lib/python3.7/lib-dynload/_bisect.cpython-37m-x86_64-linux-gnu.so
7f98446d8000-7f98448d7000 ---p 00002000 08:01 23337879                   /usr/local/lib/python3.7/lib-dynload/_bisect.cpython-37m-x86_64-linux-gnu.so
7f98448d7000-7f98448d8000 r--p 00001000 08:01 23337879                   /usr/local/lib/python3.7/lib-dynload/_bisect.cpython-37m-x86_64-linux-gnu.so
7f98448d8000-7f98448d9000 rw-p 00002000 08:01 23337879                   /usr/local/lib/python3.7/lib-dynload/_bisect.cpython-37m-x86_64-linux-gnu.so
7f98448d9000-7f98448ef000 r-xp 00000000 08:01 23337851                   /usr/local/lib/python3.7/lib-dynload/_sha3.cpython-37m-x86_64-linux-gnu.so
7f98448ef000-7f9844aee000 ---p 00016000 08:01 23337851                   /usr/local/lib/python3.7/lib-dynload/_sha3.cpython-37m-x86_64-linux-gnu.so
7f9844aee000-7f9844aef000 r--p 00015000 08:01 23337851                   /usr/local/lib/python3.7/lib-dynload/_sha3.cpython-37m-x86_64-linux-gnu.so
7f9844aef000-7f9844af1000 rw-p 00016000 08:01 23337851                   /usr/local/lib/python3.7/lib-dynload/_sha3.cpython-37m-x86_64-linux-gnu.so
7f9844af1000-7f9844afb000 r-xp 00000000 08:01 23337909                   /usr/local/lib/python3.7/lib-dynload/_blake2.cpython-37m-x86_64-linux-gnu.so
7f9844afb000-7f9844cfa000 ---p 0000a000 08:01 23337909                   /usr/local/lib/python3.7/lib-dynload/_blake2.cpython-37m-x86_64-linux-gnu.so
7f9844cfa000-7f9844cfb000 r--p 00009000 08:01 23337909                   /usr/local/lib/python3.7/lib-dynload/_blake2.cpython-37m-x86_64-linux-gnu.so
7f9844cfb000-7f9844cfc000 rw-p 0000a000 08:01 23337909                   /usr/local/lib/python3.7/lib-dynload/_blake2.cpython-37m-x86_64-linux-gnu.so
7f9844cfc000-7f9844f16000 r-xp 00000000 08:01 18092616                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f9844f16000-7f9845115000 ---p 0021a000 08:01 18092616                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f9845115000-7f9845131000 r--p 00219000 08:01 18092616                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f9845131000-7f984513d000 rw-p 00235000 08:01 18092616                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f984513d000-7f9845140000 rw-p 00000000 00:00 0 
7f9845140000-7f9845146000 r-xp 00000000 08:01 23337889                   /usr/local/lib/python3.7/lib-dynload/_hashlib.cpython-37m-x86_64-linux-gnu.so
7f9845146000-7f9845345000 ---p 00006000 08:01 23337889                   /usr/local/lib/python3.7/lib-dynload/_hashlib.cpython-37m-x86_64-linux-gnu.so
7f9845345000-7f9845346000 r--p 00005000 08:01 23337889                   /usr/local/lib/python3.7/lib-dynload/_hashlib.cpython-37m-x86_64-linux-gnu.so
7f9845346000-7f9845347000 rw-p 00006000 08:01 23337889                   /usr/local/lib/python3.7/lib-dynload/_hashlib.cpython-37m-x86_64-linux-gnu.so
7f9845347000-7f98453c7000 rw-p 00000000 00:00 0 
7f98453c7000-7f9845406000 r-xp 00000000 08:01 23337854                   /usr/local/lib/python3.7/lib-dynload/pyexpat.cpython-37m-x86_64-linux-gnu.so
7f9845406000-7f9845605000 ---p 0003f000 08:01 23337854                   /usr/local/lib/python3.7/lib-dynload/pyexpat.cpython-37m-x86_64-linux-gnu.so
7f9845605000-7f9845607000 r--p 0003e000 08:01 23337854                   /usr/local/lib/python3.7/lib-dynload/pyexpat.cpython-37m-x86_64-linux-gnu.so
7f9845607000-7f9845609000 rw-p 00040000 08:01 23337854                   /usr/local/lib/python3.7/lib-dynload/pyexpat.cpython-37m-x86_64-linux-gnu.so
7f9845609000-7f9845623000 r-xp 00000000 08:01 23337881                   /usr/local/lib/python3.7/lib-dynload/_datetime.cpython-37m-x86_64-linux-gnu.so
7f9845623000-7f9845822000 ---p 0001a000 08:01 23337881                   /usr/local/lib/python3.7/lib-dynload/_datetime.cpython-37m-x86_64-linux-gnu.so
7f9845822000-7f9845823000 r--p 00019000 08:01 23337881                   /usr/local/lib/python3.7/lib-dynload/_datetime.cpython-37m-x86_64-linux-gnu.so
7f9845823000-7f9845826000 rw-p 0001a000 08:01 23337881                   /usr/local/lib/python3.7/lib-dynload/_datetime.cpython-37m-x86_64-linux-gnu.so
7f9845826000-7f9845866000 rw-p 00000000 00:00 0 
7f9845866000-7f9845870000 r-xp 00000000 08:01 23337900                   /usr/local/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so
7f9845870000-7f9845a6f000 ---p 0000a000 08:01 23337900                   /usr/local/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so
7f9845a6f000-7f9845a70000 r--p 00009000 08:01 23337900                   /usr/local/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so
7f9845a70000-7f9845a72000 rw-p 0000a000 08:01 23337900                   /usr/local/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so
7f9845a72000-7f9845a79000 r-xp 00000000 08:01 23337892                   /usr/local/lib/python3.7/lib-dynload/select.cpython-37m-x86_64-linux-gnu.so
7f9845a79000-7f9845c78000 ---p 00007000 08:01 23337892                   /usr/local/lib/python3.7/lib-dynload/select.cpython-37m-x86_64-linux-gnu.so
7f9845c78000-7f9845c79000 r--p 00006000 08:01 23337892                   /usr/local/lib/python3.7/lib-dynload/select.cpython-37m-x86_64-linux-gnu.so
7f9845c79000-7f9845c7b000 rw-p 00007000 08:01 23337892                   /usr/local/lib/python3.7/lib-dynload/select.cpython-37m-x86_64-linux-gnu.so
7f9845c7b000-7f9845c7e000 r-xp 00000000 08:01 23337910                   /usr/local/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so
7f9845c7e000-7f9845e7d000 ---p 00003000 08:01 23337910                   /usr/local/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so
7f9845e7d000-7f9845e7e000 r--p 00002000 08:01 23337910                   /usr/local/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so
7f9845e7e000-7f9845e7f000 rw-p 00003000 08:01 23337910                   /usr/local/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so
7f9845e7f000-7f9845ebf000 rw-p 00000000 00:00 0 
7f9845ec8000-7f9845f08000 rw-p 00000000 00:00 0 
7f9845f08000-7f9845f0e000 r-xp 00000000 08:01 23337845                   /usr/local/lib/python3.7/lib-dynload/binascii.cpython-37m-x86_64-linux-gnu.so
7f9845f0e000-7f984610d000 ---p 00006000 08:01 23337845                   /usr/local/lib/python3.7/lib-dynload/binascii.cpython-37m-x86_64-linux-gnu.so
7f984610d000-7f984610e000 r--p 00005000 08:01 23337845                   /usr/local/lib/python3.7/lib-dynload/binascii.cpython-37m-x86_64-linux-gnu.so
7f984610e000-7f984610f000 rw-p 00006000 08:01 23337845                   /usr/local/lib/python3.7/lib-dynload/binascii.cpython-37m-x86_64-linux-gnu.so
7f984610f000-7f9846119000 r-xp 00000000 08:01 23337849                   /usr/local/lib/python3.7/lib-dynload/_struct.cpython-37m-x86_64-linux-gnu.so
7f9846119000-7f9846319000 ---p 0000a000 08:01 23337849                   /usr/local/lib/python3.7/lib-dynload/_struct.cpython-37m-x86_64-linux-gnu.so
7f9846319000-7f984631a000 r--p 0000a000 08:01 23337849                   /usr/local/lib/python3.7/lib-dynload/_struct.cpython-37m-x86_64-linux-gnu.so
7f984631a000-7f984631d000 rw-p 0000b000 08:01 23337849                   /usr/local/lib/python3.7/lib-dynload/_struct.cpython-37m-x86_64-linux-gnu.so
7f984631d000-7f984631f000 r-xp 00000000 08:01 23337848                   /usr/local/lib/python3.7/lib-dynload/grp.cpython-37m-x86_64-linux-gnu.so
7f984631f000-7f984651e000 ---p 00002000 08:01 23337848                   /usr/local/lib/python3.7/lib-dynload/grp.cpython-37m-x86_64-linux-gnu.so
7f984651e000-7f984651f000 r--p 00001000 08:01 23337848                   /usr/local/lib/python3.7/lib-dynload/grp.cpython-37m-x86_64-linux-gnu.so
7f984651f000-7f9846520000 rw-p 00002000 08:01 23337848                   /usr/local/lib/python3.7/lib-dynload/grp.cpython-37m-x86_64-linux-gnu.so
7f9846520000-7f9846560000 rw-p 00000000 00:00 0 
7f9846560000-7f9846579000 r-xp 00000000 08:01 18092799                   /lib/x86_64-linux-gnu/libz.so.1.2.8
7f9846579000-7f9846778000 ---p 00019000 08:01 18092799                   /lib/x86_64-linux-gnu/libz.so.1.2.8
7f9846778000-7f9846779000 r--p 00018000 08:01 18092799                   /lib/x86_64-linux-gnu/libz.so.1.2.8
7f9846779000-7f984677a000 rw-p 00019000 08:01 18092799                   /lib/x86_64-linux-gnu/libz.so.1.2.8
7f984677a000-7f9846780000 r-xp 00000000 08:01 23337867                   /usr/local/lib/python3.7/lib-dynload/zlib.cpython-37m-x86_64-linux-gnu.so
7f9846780000-7f9846980000 ---p 00006000 08:01 23337867                   /usr/local/lib/python3.7/lib-dynload/zlib.cpython-37m-x86_64-linux-gnu.so
7f9846980000-7f9846981000 r--p 00006000 08:01 23337867                   /usr/local/lib/python3.7/lib-dynload/zlib.cpython-37m-x86_64-linux-gnu.so
7f9846981000-7f9846983000 rw-p 00007000 08:01 23337867                   /usr/local/lib/python3.7/lib-dynload/zlib.cpython-37m-x86_64-linux-gnu.so
7f9846983000-7f9846a83000 rw-p 00000000 00:00 0 
7f9846a83000-7f9846a86000 r-xp 00000000 08:01 23337918                   /usr/lo`

How can i fix it?

**Comment by D4Vinci** [comment]
Three questions:
1. Have you followed all the installation instructions in the readme ?
2. What os you use ?
3. Which python version you use ?

**Comment by devil67** [comment]
Yes i have follow all the instructions.Anyway i use Linux backbox 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
i use Python 3.7.1

i try pip install gnureadline it's miracle...This was incredibly helpful. Thanks!

**Comment by D4Vinci** [comment]
Okay, thanks!
I will add it to the README file :smile:
