### ISSUE TITLE
System based on Ubuntu does not work

### ISSUE THREAD

**Issue by MontoyaAndres** [D4Vinci/PasteJacker#3]
I'm using Linux Mint, based on Ubuntu 18, when I copy the text and I paste it, the script in the background is not executed... But if I tried on Debian based system, it works!

I've been looking and is because in the Debian /dev/null exists, Ubuntu not... There's other way to use pastejaking in these linux os?

Thanks!

**Comment by D4Vinci** [comment]
Hey!
/dev/null is in every Linux distro and you can google it to see by yourself!

**Comment by MontoyaAndres** [comment]
Try /dev/null on Linux mint
